name: Image

on:
  push:

env:
  DOCKER_IMAGE_TAG: strangesast/fwlib

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      id: buildx
      with:
        install: true

    - name: Available platforms
      run: echo ${{ steps.buildx.outputs.platforms }}

    - name: Login
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

    - name: Build
      run: docker build . --platforms=linux/amd64,linux/arm/v7,linux/aarch64,linux/386 -f Dockerfile -t $DOCKER_IMAGE_TAG

    - name: Push
      run: docker push $DOCKER_IMAGE_TAG
