name: WindowsImage

on:
  push:
    paths:
      - '.github/workflows/image.yml'
      - 'windows.Dockerfile'

env:
  DOCKER_IMAGE_TAG: strangesast/fwlib-windows

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Login
      shell: powershell
      env:
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      run: Write-Output ${env:DOCKERHUB_PASSWORD} | docker login --username ${env:DOCKERHUB_USERNAME} --password-stdin

    - name: Build
      shell: powershell
      run: docker build . -f windows.Dockerfile -t ${env:DOCKER_IMAGE_TAG}

    - name: Push
      shell: powershell
      run: docker push ${env:DOCKER_IMAGE_TAG}
