name: WindowsImage

on:
  push:

env:
  DOCKER_IMAGE_TAG: strangesast/fwlib-windows

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Login
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

    - name: Build
      run: docker build . -f windows.Dockerfile -t $DOCKER_IMAGE_TAG

    - name: Push
      run: docker push $DOCKER_IMAGE_TAG
